FROM node:10-alpine
COPY . /workspace
WORKDIR /workspace
RUN npm install
RUN npm run build


FROM nginx:1.17-alpine
RUN apk add --update nodejs npm git

COPY nginx/default.conf /etc/nginx/conf.d/

RUN mkdir -p /usr/share/nginx/html && mkdir -p /usr/share/nginx/landing &&  rm -rf /usr/share/nginx/html/* && rm -rf /usr/share/nginx/landing/*

COPY --from=0 /workspace/dist /usr/share/nginx/html
EXPOSE 8080:80

CMD ["nginx", "-g", "daemon off;"]
