version: '2'
services:
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - ./mysql/database:/var/lib/mysql
    ports:
      - "3306:3306"
  
  testhub_api:
    container_name: test_hub_api
    restart: always
    build: 
      context: ./TestsHub/
      dockerfile: TestsHub.Api/Dockerfile
    ports: 
        - "80:80"
        - "443:443"
volumes:
  my-datavolume: