{{- $fullName := include "testhub.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: testhub-frontend
  labels:
    {{- include "testhub.labels" . | nindent 4 }}
  {{- with .Values.ingress.frontend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.frontend.tls }}
  tls:
    {{- range .Values.ingress.frontend.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:    
    - host: {{ .Values.ingress.frontend.host }}
      http:
        paths:          
          - path: /
            backend:
              serviceName: testhub-frontend
              servicePort: 8080
          
    
