apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "testhub.labels" . | nindent 4 }}
  name: testhub-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
  selector:
    app: testhub-api
status:
  loadBalancer: {}
