version: '3'

services:
  testhub-api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of .NET: 5.0, 3.1, 2.1
        VARIANT: "3.1"        
        NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  testhub-frontend:
    container_name: testhub-frontend
    build: 
      context: ../../frontend/
      dockerfile: Dockerfile-build

    restart: always    
    ports:
      - "8080:80"

    
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql


volumes:
  my-db: