name: Backend
on:  
  push:
    paths: 
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: backend

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: ${{ env.working-directory }}
      run: dotnet restore

    - name: Build
      working-directory: ${{ env.working-directory }}
      run: dotnet build --no-restore
    
    - name: Test
      working-directory: ${{ env.working-directory }}
      run: dotnet test --no-build --verbosity normal --logger "junit;LogFilePath=TestResults/th-test-results.xml" --filter  TestCategory!=Integration --collect:"XPlat Code Coverage"      
    
    - name: Upload test results      
      uses: testhub-io/testhub-io.action@v0.61      
      with:        
        test_result_pattern: "**/TestResults/th-test-results.xml"
        test_coverage_pattern: "**/coverage.cobertura.xml"
        base_directory: ${{ env.working-directory }}
              
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2      
      with:
        push: true
        tags: |
           testhubio/testhub-api:latest   
           testhubio/testhub-api:${{ github.run_number	}}
        file: ${{ env.working-directory }}/TestsHub.Api/Dockerfile
        context: ${{ env.working-directory }}

        
