name: .NET
on:  push   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "junit;LogFilePath=TestResults/th-test-results.xml" --filter  TestCategory!=Integration --collect:"XPlat Code Coverage"

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@e1b7f96249f2e4c8e4ac1519b9608c0d48944a1f
      uses: docker/build-push-action@v2.4.0
      with:                
        repository: 'testhubio/testhub-api'
        tag_with_ref: true        
        file: ./TestsHub.Api/Dockerfile
        
