# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend
on:  
  push:
    paths: 
      - "frontend/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: frontend

    strategy:
      matrix:
        node-version: [ 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}    
    - run: npm ci
      working-directory: ${{ env.working-directory }}

    - run: npm run build --if-present
      working-directory: ${{ env.working-directory }}

    - run: npm run test --if-present
      working-directory: ${{ env.working-directory }}

    - run: npm run deploy
      working-directory: ${{ env.working-directory }}
    

    - name: Init vars 
      id: vars_step
      run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    
    - name: Buildah login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: buildah login -u $DOCKER_USERNAME -p "$DOCKER_PASSWORD" docker.io/testhubio

      
    - name: Push testhubio/frontend image
      run: buildah bud -t testhubio/frontend:${{ steps.vars_step.outputs.sha_short }} -t testhubio/frontend:latest  ${{ env.working-directory }}
    - name: Push testhubio/frontend image
      run: |                      
            buildah push testhubio/frontend:${{ steps.vars_step.outputs.sha_short }} && \
            buildah push testhubio/frontend:latest 

    - name: Build testhubio/frontend on-prem image
      run: buildah bud -f Dockerfile-on-prem.dockerfile -t testhubio/frontend:${{ steps.vars_step.outputs.sha_short }}-on-prem -t testhubio/frontend:latest-on-prem -t testhubio/frontend:on-prem ${{ env.working-directory }}     
    - name: Push testhubio/frontend on-prem image
      run: |  
            buildah push testhubio/frontend:${{ steps.vars_step.outputs.sha_short }}-on-prem && \
            buildah push testhubio/frontend:on-prem  &&  \
            buildah push testhubio/frontend:latest-on-prem  
    
