
name: Release Charts

on:
  push:
    branches:
      - main
      - helm-chart
    paths: 
      - "helm/**"
      - ".github/workflows/helm-chart.yml"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - name: Create release
        working-directory: ./helm
        run: helm package testhub

      - name: Pushes helm release file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'teshub-*.tgz'
          destination_repo: 'testhub-io/testhub-helm'
          #destination_folder: 'test-dir'
          user_email: 'bot@test-hub.io'
          user_name: 'TesthubBot'
          commit_message: 'New version of Testhub helm chart'

