# .github/workflows/release.yaml

on: release
name: Build Release
jobs:
  
  release:
    name: alternative-amd64
    runs-on: ubuntu-latest
    steps:      
       - uses: actions/checkout@master        
       - name: linux-amd64
         uses: wangyoucao577/go-release-action@v1.14
         with:            
            github_token:  ${{ secrets.GITHUB_TOKEN }}            
            goos: linux            
            goarch:  amd64
       - name: linux-386
         uses: wangyoucao577/go-release-action@v1.14
         with:            
            github_token:  ${{ secrets.GITHUB_TOKEN }}            
            goos: linux            
            goarch: 386
       - name: darwin-amd64
         uses: wangyoucao577/go-release-action@v1.14
         with:            
            github_token:  ${{ secrets.GITHUB_TOKEN }}            
            goos: darwin            
            goarch: amd64  
       - name: windows-386
         uses: wangyoucao577/go-release-action@v1.14
         with:            
            github_token:  ${{ secrets.GITHUB_TOKEN }}            
            goos: windows
            goarch: 386 
       - name: windows-amd64
         uses: wangyoucao577/go-release-action@v1.14
         with:            
            github_token:  ${{ secrets.GITHUB_TOKEN }}            
            goos: windows
            goarch: amd64 
      
